---
    - name: copy ssh-keys
      copy:
        src: ~/.ssh/
        dest: ~/.ssh/
        owner: $USER
        group: $GROUP
        mode: 0600

    - name: Copy hosts config files
      template:
        src: "hosts"
        dest: "/etc/hosts"
      become: yes

