all:
  hosts:
  children:
    nginx_test:
      hosts:
        app_node_exporter:
          ansible_ssh_host: 192.168.2.6
          ansible_user: "mike"
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
        postgres:
          ansible_ssh_host: 192.168.2.8
          ansible_user: "mike"
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
        elastic:
          ansible_ssh_host: 192.168.2.7
          ansible_user: "mike"
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"

