---
    - name: Reset Kubernetes component
      shell: "sudo kubeadm reset --force"
      become: yes
      ignore_errors: True

    - name: Delete dir /home/mike/.kube
      shell: "rm -rf /home/mike/.kube"

    - name: copy connectworker-node.sh
      copy:
        src: /home/mike/course-devops/kubernetes/ansible/kube0/home/mike/connectworker-node.sh
        dest: ~/
        owner: mike
        group: mike
        mode: 0777

    - name: Run script connectworker-node.sh
      shell: "~/connectworker-node.sh"

#    - name: mkdir -p $HOME/.kube
#      shell: "mkdir -p $HOME/.kube"

#    - name: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
#      shell: "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"

#    - name: sudo chown $(id -u):$(id -g) $HOME/.kube/config
#      shell: "sudo chown $(id -u):$(id -g) $HOME/.kube/config"

#    - name: Not ready > Ready cluster
#      shell: ssh {{internal_ip_kube0}} "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
#      register: ready
#      become: yes
#    - debug: var=ready_nodes.stdout

#    - name: Kubectl get nodes
#      shell: ssh {{internal_ip_kube0}} "kubectl get nodes"
#      register: get_nodes
#      become: yes
#    - debug: var=get_nodes.stdout_lines
